#!/usr/bin/env python3
"""Generate compact float32 tables for the Model_train MFCC frontend."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import sys
import json
import hashlib

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from shared.deployment_contract import CONTRACT, CONTRACT_SHA256, render_c_header



SAMPLE_RATE = CONTRACT['audio']['sample_rate_hz']
FFT_SIZE = CONTRACT['stft']['fft_size']
MEL_BANDS = CONTRACT['mel']['mfcc_bands']
MFCC_COEFFICIENTS = CONTRACT['mfcc']['coefficients']
SPECTRAL_BANDS = CONTRACT['mel']['spectral_bands']


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", required=True, type=Path)
    return parser.parse_args()


def hz_to_mel(frequencies: np.ndarray) -> np.ndarray:
    frequencies = np.asarray(frequencies, dtype=np.float64)
    mels = 3.0 * frequencies / 200.0
    minimum_log_hz = 1_000.0
    minimum_log_mel = 15.0
    log_step = np.log(6.4) / 27.0
    logarithmic = frequencies >= minimum_log_hz
    mels[logarithmic] = minimum_log_mel + np.log(
        frequencies[logarithmic] / minimum_log_hz
    ) / log_step
    return mels


def mel_to_hz(mels: np.ndarray) -> np.ndarray:
    mels = np.asarray(mels, dtype=np.float64)
    frequencies = 200.0 * mels / 3.0
    minimum_log_hz = 1_000.0
    minimum_log_mel = 15.0
    log_step = np.log(6.4) / 27.0
    logarithmic = mels >= minimum_log_mel
    frequencies[logarithmic] = minimum_log_hz * np.exp(
        log_step * (mels[logarithmic] - minimum_log_mel)
    )
    return frequencies


def mel_filterbank(mel_bands: int) -> np.ndarray:
    mel_edges = mel_to_hz(
        np.linspace(
            hz_to_mel(np.asarray([CONTRACT["mel"]["fmin"]]))[0],
            hz_to_mel(np.asarray([CONTRACT["mel"]["fmax"]]))[0],
            mel_bands + 2,
        )
    )
    fft_frequencies = np.fft.rfftfreq(FFT_SIZE, 1.0 / SAMPLE_RATE)
    frequency_differences = np.diff(mel_edges)
    ramps = np.subtract.outer(mel_edges, fft_frequencies)
    weights = np.zeros((mel_bands, FFT_SIZE // 2 + 1), dtype=np.float32)
    for band in range(mel_bands):
        lower = -ramps[band] / frequency_differences[band]
        upper = ramps[band + 2] / frequency_differences[band + 1]
        weights[band] = np.maximum(0.0, np.minimum(lower, upper))
    weights *= (2.0 / (mel_edges[2:] - mel_edges[:-2]))[:, np.newaxis]
    return weights


def dct_matrix() -> np.ndarray:
    samples = np.arange(MEL_BANDS, dtype=np.float64)
    coefficients = np.arange(MFCC_COEFFICIENTS, dtype=np.float64)[:, np.newaxis]
    matrix = np.cos(
        np.pi
        * coefficients
        * (2.0 * samples + 1.0)
        / (2.0 * MEL_BANDS)
    )
    matrix *= np.sqrt(2.0 / MEL_BANDS)
    matrix[0] = 1.0 / np.sqrt(MEL_BANDS)
    return matrix.astype(np.float32)


def c_float(value: np.float32) -> str:
    return float(value).hex() + "f"


def render_array(
    c_type: str,
    name: str,
    values: list[int] | np.ndarray,
    *,
    per_line: int,
) -> str:
    rendered = [
        str(int(value)) if c_type != "float" else c_float(np.float32(value))
        for value in values
    ]
    lines = [
        "    " + ", ".join(rendered[index : index + per_line]) + ","
        for index in range(0, len(rendered), per_line)
    ]
    return (
        f"const {c_type} {name}[{len(rendered)}] = {{\n"
        + "\n".join(lines)
        + "\n};\n"
    )


def main() -> int:
    args = parse_args()
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    window = (
        0.5
        - 0.5
        * np.cos(
            2.0 * np.pi * np.arange(FFT_SIZE, dtype=np.float64) / FFT_SIZE
        )
    ).astype(np.float32)
    sparse_tables: dict[
        int, tuple[list[int], list[int], list[np.float32]]
    ] = {}
    for mel_bands in (MEL_BANDS, SPECTRAL_BANDS):
        weights = mel_filterbank(mel_bands)
        starts: list[int] = []
        offsets = [0]
        sparse_weights: list[np.float32] = []
        for band in range(mel_bands):
            nonzero = np.flatnonzero(weights[band])
            if len(nonzero) == 0:
                raise RuntimeError(f"Mel band {band} has no FFT bins")
            start = int(nonzero[0])
            stop = int(nonzero[-1]) + 1
            starts.append(start)
            sparse_weights.extend(weights[band, start:stop])
            offsets.append(len(sparse_weights))
        sparse_tables[mel_bands] = (starts, offsets, sparse_weights)

    starts, offsets, sparse_weights = sparse_tables[MEL_BANDS]
    starts_40, offsets_40, sparse_weights_40 = sparse_tables[SPECTRAL_BANDS]

    header = """/* Generated by tools/generate_mfcc_frontend_tables.py. */
#ifndef MFCC_FRONTEND_TABLES_H
#define MFCC_FRONTEND_TABLES_H

#include <stdint.h>

#define MFCC_TABLE_FFT_SIZE 2048U
#define MFCC_TABLE_MEL_BANDS 128U
#define MFCC_TABLE_COEFFICIENTS 13U
#define MFCC_TABLE_WEIGHT_COUNT %dU
#define SPECTRAL_TABLE_MEL_BANDS 40U
#define SPECTRAL_TABLE_WEIGHT_COUNT %dU

extern const float mfcc_hann_window[MFCC_TABLE_FFT_SIZE];
extern const uint16_t mfcc_mel_starts[MFCC_TABLE_MEL_BANDS];
extern const uint16_t mfcc_mel_offsets[MFCC_TABLE_MEL_BANDS + 1U];
extern const float mfcc_mel_weights[MFCC_TABLE_WEIGHT_COUNT];
extern const float
    mfcc_dct_matrix[MFCC_TABLE_COEFFICIENTS * MFCC_TABLE_MEL_BANDS];
extern const uint16_t spectral_mel_starts[SPECTRAL_TABLE_MEL_BANDS];
extern const uint16_t spectral_mel_offsets[SPECTRAL_TABLE_MEL_BANDS + 1U];
extern const float spectral_mel_weights[SPECTRAL_TABLE_WEIGHT_COUNT];

#endif /* MFCC_FRONTEND_TABLES_H */
""" % (len(sparse_weights), len(sparse_weights_40))

    header = header.replace('FFT_SIZE 2048U', f'FFT_SIZE {FFT_SIZE}U').replace('MEL_BANDS 128U', f'MEL_BANDS {MEL_BANDS}U').replace('COEFFICIENTS 13U', f'COEFFICIENTS {MFCC_COEFFICIENTS}U').replace('MEL_BANDS 40U', f'MEL_BANDS {SPECTRAL_BANDS}U')
    (output_dir / 'shared_frontend_contract.h').write_text(render_c_header(CONTRACT), encoding='utf-8')
    (output_dir / 'frontend_contract.json').write_text(json.dumps({'frontend_contract_sha256': CONTRACT_SHA256, 'contract': CONTRACT}, indent=2), encoding='utf-8')

    source = """/* Generated by tools/generate_mfcc_frontend_tables.py. */
#include "mfcc_frontend_tables.h"

"""
    source += render_array(
        "float", "mfcc_hann_window", window, per_line=4
    )
    source += "\n" + render_array(
        "uint16_t", "mfcc_mel_starts", starts, per_line=12
    )
    source += "\n" + render_array(
        "uint16_t", "mfcc_mel_offsets", offsets, per_line=12
    )
    source += "\n" + render_array(
        "float",
        "mfcc_mel_weights",
        np.asarray(sparse_weights, dtype=np.float32),
        per_line=4,
    )
    source += "\n" + render_array(
        "float", "mfcc_dct_matrix", dct_matrix().reshape(-1), per_line=4
    )
    source += "\n" + render_array(
        "uint16_t", "spectral_mel_starts", starts_40, per_line=12
    )
    source += "\n" + render_array(
        "uint16_t", "spectral_mel_offsets", offsets_40, per_line=12
    )
    source += "\n" + render_array(
        "float",
        "spectral_mel_weights",
        np.asarray(sparse_weights_40, dtype=np.float32),
        per_line=4,
    )

    (output_dir / "mfcc_frontend_tables.h").write_text(
        header, encoding="utf-8"
    )
    (output_dir / "mfcc_frontend_tables.c").write_text(
        source, encoding="utf-8"
    )
    print(
        "generated frontend tables: "
        f"{len(sparse_weights)} MFCC and {len(sparse_weights_40)} "
        "LogMel/PCEN sparse Mel weights"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
